### ISSUE TITLE
 Unable to determine a suitable edition, even after broadening.

### ISSUE THREAD

**Issue by jairayafranco** [soulsam480/vite-electron-react-starter#2]
I got this error when i use "npm run compile", it works perfectly with "npm run watch"

![image](https://user-images.githubusercontent.com/54295211/146698732-c98f6012-62fd-45d3-9b32-ea0327bb3cec.png)

**Comment by soulsam480** [comment]
hey @jairayafranco I'm not maintaining this anymore. Really sorry, the upstream https://github.com/cawa-93/vite-electron-builder has many new commits and fixes, Can you pull in those changes and check ?

**Comment by soulsam480** [comment]
I'll try to find some time and merge those changes from upstream this week.

**Comment by theogravity** [comment]
@soulsam480 I did my best to kind of combine the example I saw here with the latest `vite-electron-react-starter`, and it's able to compile and run, but I can't seem to get hmr working.

If you want to take a stab at it, I have my version here

https://github.com/theogravity/react-electron-builder

I've tried `import react from '@vitejs/plugin-react';` and the refresh version that some projects seem to use.

**Comment by soulsam480** [comment]
Thanks will try to check.

**Comment by theogravity** [comment]
@soulsam480 figured it out. my import had the wrong casing in the `app.tsx` file. You would think it would complain about the case, but guess not.

`import App from '/@/app';` 

vs

`import App from '/@/App';` (had to make sure the file itself matched the casing)

I've updated my repo if you want to copy it over, i don't mind!

**Comment by soulsam480** [comment]
Thanks. Will do that.

**Comment by theogravity** [comment]
New url is 

https://github.com/theogravity/react-vite-electron-builder

I didn't do a fork on the other repo and felt odd to not have the commit history, so here it is again with the commit history

This is the specific changeset

https://github.com/theogravity/react-vite-electron-builder/commit/4774bfe9e4e4c7f27c24614fe235859def290e34

https://github.com/theogravity/react-vite-electron-builder/commit/4774bfe9e4e4c7f27c24614fe235859def290e34.patch

**Comment by soulsam480** [comment]
@theogravity Hey, thanks for all the help. Is it ok If I invite you to this repo and you can make the changes ? I hardly find any time these days. Really appreciate your help.

**Comment by theogravity** [comment]
I don't mind, and will remove my repo after migrating. However, the dir structure has changed so much compared to base in this repo that there would probably be a ton of merge conflicts coming in.

What do you think would be the best way to go about this? Force push the base repo + patch to make sure the commit history is current with base?

I would definitely fix what I have to include the original CSS and assets to be in line with the original.

**Comment by soulsam480** [comment]
> What do you think would be the best way to go about this? Force push the base repo + patch to make sure the commit history is current with base?

I think we can do a force-push. Most of the user who have created projects from this won't be pulling it. So it's fine

**Comment by soulsam480** [comment]
@theogravity sent you an invitation. Again thanks for your help

**Comment by theogravity** [comment]
Ported over, including the original templates!

<img width="797" alt="CleanShot 2021-12-27 at 00 47 06@2x" src="https://user-images.githubusercontent.com/855434/147453626-1024042c-8165-4524-8259-1cf1c2725cb6.png">
